# Generated by Django 3.2.12 on 2024-11-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('days_in_cycle', models.DecimalField(decimal_places=10, default=365, max_digits=10)),
                ('repeats', models.BooleanField(default=False)),
                ('color', models.CharField(default='#0000FF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_day', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('end_day', models.DecimalField(decimal_places=10, default=365, max_digits=10)),
                ('color', models.CharField(default='#FF00FF', max_length=7)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eras', to='woy.circle')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('degree', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('day', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='woy.circle')),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woy.era')),
            ],
        ),
    ]
