# Generated by Django 3.2.12 on 2024-11-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='days_in_cycle',
            field=models.DecimalField(decimal_places=10, default=365, max_digits=20),
        ),
        migrations.AlterField(
            model_name='era',
            name='end_day',
            field=models.DecimalField(decimal_places=10, default=365, max_digits=20),
        ),
        migrations.AlterField(
            model_name='era',
            name='start_day',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='degree',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
