# Generated by Django 5.1.6 on 2025-03-02 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woy", "0002_auto_20241107_0207"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "inner_radius",
                    models.DecimalField(decimal_places=10, default=50, max_digits=20),
                ),
                (
                    "thickness",
                    models.DecimalField(decimal_places=10, default=20, max_digits=20),
                ),
                ("number_of_ticks", models.IntegerField(default=365)),
                ("base_color", models.CharField(default="#00FF00", max_length=7)),
                ("use_images", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RingEra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "start_day",
                    models.DecimalField(decimal_places=10, default=0, max_digits=20),
                ),
                (
                    "end_day",
                    models.DecimalField(decimal_places=10, default=365, max_digits=20),
                ),
                ("color", models.CharField(default="#FF00FF", max_length=7)),
                (
                    "ring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eras",
                        to="woy.ring",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(max_length=500)),
                ("order", models.IntegerField(default=0)),
                (
                    "ring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="woy.ring",
                    ),
                ),
            ],
        ),
    ]
