# Generated by Django 5.1.6 on 2025-03-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woy", "0003_ring_ringera_ringimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="era",
            name="circle",
        ),
        migrations.RemoveField(
            model_name="event",
            name="circle",
        ),
        migrations.RemoveField(
            model_name="event",
            name="era",
        ),
        migrations.AlterField(
            model_name="ringimage",
            name="image_path",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Circle",
        ),
        migrations.DeleteModel(
            name="Era",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
