# Generated by Django 5.1.6 on 2025-03-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woy", "0005_ring_created_by_ring_is_public_userringpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ring",
            name="index",
            field=models.IntegerField(help_text="Position in the display order"),
        ),
    ]
